
from PyQt6.QtCore import QObject, pyqtSignal

class LanguageManager(QObject):
    language_changed = pyqtSignal()
    
    TRANSLATIONS = {
        "en": {
            "window_title": "P2P File Sharing App",
            "tab_send": "Send",
            "tab_receive": "Receive",
            "tab_history": "History",
            "tab_chat": "Chat",
            "tab_mobile": "Mobile",
            "label_language": "Language:",
            "select_files": "Select Files",
            "select_folder": "Select Folder",
            "clear_files": "Clear Files",
            "discovered_receivers": "Discovered Receivers:",
            "search_receivers": "Search Receivers",
            "searching": "Searching...",
            "connect": "Connect",
            "disconnect": "Disconnect",
            "send": "Send",
            "pause": "Pause",
            "resume": "Resume",
            "cancel_transfer": "Cancel Transfer",
            "selected_prefix": "Selected: ",
            "selected_none": "Selected: none",
            "connection_disconnected": "Connection: Disconnected",
            "connection_connecting": "Connection: Connecting to {}",
            "connection_transfer_complete": "Connection: Transfer completed. Idle.",
            "auto_refresh": "Auto-refresh receivers",
            "enable_compression": "Enable Compression (zip before sending)",
            "progress_prefix": "Progress: ",
            "listen_port_placeholder": "Listen Port (5000)",
            "start_receiving": "Start Receiving",
            "stop_receiving": "Stop Receiving",
            "set_save_folder": "Set Save Folder",
            "auto_accept": "Auto-accept all (connections + file transfers)",
            "received_files_label": "Received Files:",
            "transfer_progress_label": "Transfer Progress:",
            "no_incoming": "No incoming requests yet.",
            "refresh_app": "Refresh App",
            "header_filename": "Filename",
            "header_size": "Size (MB)",
            "header_md5": "MD5 (Preview)",
            "header_status": "Status",
            "header_path": "Path",
            "header_timestamp": "Time",
            "header_direction": "Type",
            "header_peer": "Peer",
            "btn_clear_history": "Clear History",
            "btn_send_chat": "Send",
            "chat_placeholder": "Type a message...",
            "chat_you": "You",
            "direction_send": "Sent",
            "direction_receive": "Received",
            "msg_history_cleared": "History Cleared",
            "msg_history_cleared_body": "Transfer history has been cleared.",
            "mode_dark": "Dark Mode",
            "mode_light": "Light Mode",
            "msg_app_refreshed": "App Refreshed",
            "msg_app_refreshed_body": "Application state has been reset.",
            "msg_limit_reached": "Limit Reached",
            "msg_limit_reached_body": "You can only select up to 50 files total.",
            "msg_no_receiver": "No Receiver Selected",
            "msg_no_receiver_body": "Please select a receiver from the list.",
            "msg_already_connected": "Already Connected",
            "msg_already_connected_body": "Already connected to a receiver.",
            "msg_not_connected": "Not Connected",
            "msg_not_connected_body": "Please connect to a receiver first.",
            "msg_no_files": "No Files",
            "msg_no_files_body": "Select files to send first.",
            "msg_all_sent": "All Sent",
            "msg_all_sent_body": "All selected files have already been sent.",
            "msg_stopped": "Stopped",
            "msg_stopped_body": "Receiving stopped successfully.",
            "msg_invalid_port": "Invalid Port",
            "msg_invalid_port_body": "Port must be a number.",
            "msg_save_folder": "Save Folder",
            "msg_save_folder_body": "Files will be saved to:\n{}",
            "msg_remove_file": "Remove File",
            "msg_remove_file_body": "Remove {} from the list?",
            "msg_no_selection": "No Selection",
            "msg_no_selection_body": "Please select a file to remove.",
            "msg_incoming_conn": "Incoming Connection",
            "msg_incoming_conn_body": "{} wants to connect and send files. Allow?",
            "msg_file_request": "File Transfer Request",
            "msg_file_request_body": "Sender wants to send {} {}. Allow?",
            "status_calculating": "Calculating...",
            "status_pending": "Pending",
            "status_receiving": "Receiving",
            "status_success": "Success",
            "status_error": "Error",
            "mobile_sent": "Sent to Mobile",
            "peer_sender": "Sender",
            "header_mobile_type": "Type",
            "header_mobile_file": "File",
            "header_mobile_size": "Size",
            "header_mobile_file": "File",
            "header_mobile_size": "Size",
            "header_mobile_time": "Time",
            "mobile_server_stopped": "Mobile Server: Stopped",
            "mobile_upload": "Mobile Upload",
            "mobile_download": "Mobile Download",
            "btn_start_mobile": "Start Mobile Server",
            "btn_stop_mobile": "Stop Server",
            "btn_set_shared": "Set Shared Folder",
            "btn_share_files": "Share Files to Mobile...",
            "mobile_folder_info": "Files in your Shared Folder are visible to mobile.",
            "mobile_hist_label": "Mobile Transfer History",
            "btn_clear_mobile": "Clear Mobile History",
            "mobile_auth_code": "Connection Code:",
            "mobile_auth_prompt": "Enter code to access files",
            "mobile_auth_device_name": "Device Name:",
            "mobile_auth_invalid": "Invalid code",
            "mobile_auth_success": "Access granted",
            "btn_reset_code": "Reset Code",
            "mobile_connections": "Authorized Devices: {0}/{1}",
            "mobile_no_devices": "No devices connected",
            "select_recipients": "Select Recipients",
            "all_devices": "All Devices",
            "recipient_dialog_title": "Choose File Recipients",
            "shared_with_all": "Shared with: All",
            "shared_with": "Shared with: {0}",
            "btn_ok": "OK",
            "btn_cancel": "Cancel"
        },
        "ru": {
            "window_title": "P2P Обмен Файлами",
            "tab_send": "Отправить",
            "tab_receive": "Получить",
            "tab_history": "История",
            "tab_chat": "Чат",
            "tab_mobile": "Мобильный",
            "label_language": "Язык:",
            "select_files": "Выбрать файлы",
            "select_folder": "Выбрать папку",
            "clear_files": "Очистить",
            "discovered_receivers": "Найденные получатели:",
            "search_receivers": "Поиск получателей",
            "searching": "Поиск...",
            "connect": "Подключиться",
            "disconnect": "Отключиться",
            "send": "Отправить",
            "pause": "Пауза",
            "resume": "Продолжить",
            "cancel_transfer": "Отмена",
            "selected_prefix": "Выбрано: ",
            "selected_none": "Выбрано: нет",
            "connection_disconnected": "Соединение: Отключено",
            "connection_connecting": "Соединение: Подключение к {}",
            "connection_transfer_complete": "Соединение: Передача завершена. Ожидание.",
            "auto_refresh": "Авто-обновление",
            "enable_compression": "Включить сжатие (zip)",
            "progress_prefix": "Прогресс: ",
            "listen_port_placeholder": "Порт (5000)",
            "start_receiving": "Начать прием",
            "stop_receiving": "Остановить прием",
            "set_save_folder": "Папка сохранения",
            "auto_accept": "Авто-прием всех",
            "received_files_label": "Полученные файлы:",
            "transfer_progress_label": "Прогресс передачи:",
            "no_incoming": "Нет входящих запросов.",
            "refresh_app": "Сброс приложения",
            "header_filename": "Имя файла",
            "header_size": "Размер (МБ)",
            "header_md5": "MD5",
            "header_status": "Статус",
            "header_path": "Путь",
            "header_timestamp": "Время",
            "header_direction": "Тип",
            "header_peer": "Участник",
            "btn_clear_history": "Очистить историю",
            "btn_send_chat": "Отправить",
            "chat_placeholder": "Введите сообщение...",
            "chat_you": "Вы",
            "direction_send": "Отправлено",
            "direction_receive": "Получено",
            "msg_history_cleared": "История очищена",
            "msg_history_cleared_body": "История передач удалена.",
            "mode_dark": "Тёмная тема",
            "mode_light": "Светлая тема",
            "msg_app_refreshed": "Сброс выполнен",
            "msg_app_refreshed_body": "Состояние приложения сброшено.",
            "msg_limit_reached": "Лимит превышен",
            "msg_limit_reached_body": "Можно выбрать максимум 50 файлов.",
            "msg_no_receiver": "Получатель не выбран",
            "msg_no_receiver_body": "Пожалуйста, выберите получателя из списка.",
            "msg_already_connected": "Уже подключено",
            "msg_already_connected_body": "Уже есть подключение к получателю.",
            "msg_not_connected": "Нет подключения",
            "msg_not_connected_body": "Сначала подключитесь к получателю.",
            "msg_no_files": "Нет файлов",
            "msg_no_files_body": "Сначала выберите файлы для отправки.",
            "msg_all_sent": "Все отправлено",
            "msg_all_sent_body": "Все выбранные файлы уже отправлены.",
            "msg_stopped": "Остановлено",
            "msg_stopped_body": "Прием остановлен успешно.",
            "msg_invalid_port": "Неверный порт",
            "msg_invalid_port_body": "Порт должен быть числом.",
            "msg_save_folder": "Папка сохранения",
            "msg_save_folder_body": "Файлы будут сохранены в:\n{}",
            "msg_remove_file": "Удалить файл",
            "msg_remove_file_body": "Удалить {} из списка?",
            "msg_no_selection": "Ничего не выбрано",
            "msg_no_selection_body": "Пожалуйста, выберите файл для удаления.",
            "msg_incoming_conn": "Входящее подключение",
            "msg_incoming_conn_body": "{} хочет подключиться и отправить файлы. Разрешить?",
            "msg_file_request": "Запрос на передачу",
            "msg_file_request_body": "Отправитель хочет передать {} {}. Разрешить?",
            "status_calculating": "Вычисление...",
            "status_pending": "Ожидание",
            "status_receiving": "Получение",
            "status_success": "Успешно",
            "status_error": "Ошибка",
            "mobile_sent": "Отправлено на телефон",
            "peer_sender": "Отправитель",
            "header_mobile_type": "Тип",
            "header_mobile_file": "Файл",
            "header_mobile_size": "Размер",
            "header_mobile_file": "Файл",
            "header_mobile_size": "Размер",
            "header_mobile_time": "Время",
            "mobile_server_stopped": "Мобильный сервер: Остановлен",
            "mobile_upload": "Загрузка с телефона",
            "mobile_download": "Скачивание на телефон",
            "btn_start_mobile": "Запустить сервер",
            "btn_stop_mobile": "Остановить",
            "btn_set_shared": "Папка для обмена",
            "btn_share_files": "Поделиться файлами...",
            "mobile_folder_info": "Файлы в общей папке видны на телефоне.",
            "mobile_hist_label": "История обмена с телефоном",
            "btn_clear_mobile": "Очистить историю",
            "mobile_auth_code": "Код подключения:",
            "mobile_auth_prompt": "Введите код для доступа",
            "mobile_auth_device_name": "Имя устройства:",
            "mobile_auth_invalid": "Неверный код",
            "mobile_auth_success": "Доступ разрешен",
            "btn_reset_code": "Сбросить код",
            "mobile_connections": "Авторизованные: {0}/{1}",
            "mobile_no_devices": "Нет подключенных устройств",
            "select_recipients": "Выбрать получателей",
            "all_devices": "Все устройства",
            "recipient_dialog_title": "Выберите получателей файлов",
            "shared_with_all": "Доступно для: Всех",
            "shared_with": "Доступно для: {0}",
            "btn_ok": "ОК",
            "btn_cancel": "Отмена"
        },
        "kk": {
            "window_title": "P2P Файл Алмасу",
            "tab_send": "Жіберу",
            "tab_receive": "Қабылдау",
            "tab_history": "Тарих",
            "tab_chat": "Чат",
            "tab_mobile": "Телефон",
            "label_language": "Тіл:",
            "select_files": "Файлдарды таңдау",
            "select_folder": "Папканы таңдау",
            "clear_files": "Тазалау",
            "discovered_receivers": "Табылған қабылдаушылар:",
            "search_receivers": "Қабылдаушыларды іздеу",
            "searching": "Іздеу...",
            "connect": "Қосылу",
            "disconnect": "Ажырату",
            "send": "Жіберу",
            "pause": "Кідірту",
            "resume": "Жалғастыру",
            "cancel_transfer": "Тоқтату",
            "selected_prefix": "Таңдалған: ",
            "selected_none": "Таңдалған: жоқ",
            "connection_disconnected": "Байланыс: Ажыратылған",
            "connection_connecting": "Байланыс: {} қосылуда",
            "connection_transfer_complete": "Байланыс: Тасымалдау аяқталды. Күтуде.",
            "auto_refresh": "Авто-жаңарту",
            "enable_compression": "Сығуды қосу (zip)",
            "progress_prefix": "Прогресс: ",
            "listen_port_placeholder": "Порт (5000)",
            "start_receiving": "Қабылдауды бастау",
            "stop_receiving": "Қабылдауды тоқтату",
            "set_save_folder": "Сақтау папкасы",
            "auto_accept": "Барлығын авто-қабылдау",
            "received_files_label": "Қабылданған файлдар:",
            "transfer_progress_label": "Тасымалдау барысы:",
            "no_incoming": "Кіріс сұраулар жоқ.",
            "refresh_app": "Қолданбаны жаңарту",
            "header_filename": "Файл аты",
            "header_size": "Өлшемі (МБ)",
            "header_md5": "MD5",
            "header_status": "Күйі",
            "header_path": "Жолы",
            "header_timestamp": "Уақыт",
            "header_direction": "Түрі",
            "header_peer": "Қатысушы",
            "btn_clear_history": "Тарихты тазалау",
            "btn_send_chat": "Жіберу",
            "chat_placeholder": "Хабарлама жазыңыз...",
            "chat_you": "Сіз",
            "direction_send": "Жіберілді",
            "direction_receive": "Қабылданды",
            "msg_history_cleared": "Тарих тазаланды",
            "msg_history_cleared_body": "Тасымалдау тарихы жойылды.",
            "mode_dark": "Қараңғы режим",
            "mode_light": "Жарық режим",
            "msg_app_refreshed": "Қолданба жаңартылды",
            "msg_app_refreshed_body": "Қолданба күйі қайта орнатылды.",
            "msg_limit_reached": "Шектеуге жетті",
            "msg_limit_reached_body": "Сіз барлығы 50 файл таңдай аласыз.",
            "msg_no_receiver": "Қабылдаушы таңдалмады",
            "msg_no_receiver_body": "Тізімнен қабылдаушыны таңдаңыз.",
            "msg_already_connected": "Байланыс орнатылған",
            "msg_already_connected_body": "Қабылдаушымен байланыс бар.",
            "msg_not_connected": "Байланыс жоқ",
            "msg_not_connected_body": "Алдымен қабылдаушыға қосылыңыз.",
            "msg_no_files": "Файлдар жоқ",
            "msg_no_files_body": "Жіберетін файлдарды таңдаңыз.",
            "msg_all_sent": "Барлығы жіберілді",
            "msg_all_sent_body": "Барлық таңдалған файлдар жіберілді.",
            "msg_stopped": "Тоқтатылды",
            "msg_stopped_body": "Қабылдау сәтті тоқтатылды.",
            "msg_invalid_port": "Жарамсыз порт",
            "msg_invalid_port_body": "Порт нөмір болуы керек.",
            "msg_save_folder": "Сақтау папкасы",
            "msg_save_folder_body": "Файлдар мұнда сақталады:\n{}",
            "msg_remove_file": "Файлды өшіру",
            "msg_remove_file_body": "Тізімнен {} өшіру керек пе?",
            "msg_no_selection": "Таңдалған ештеңе жоқ",
            "msg_no_selection_body": "Өшіру үшін файлды таңдаңыз.",
            "msg_incoming_conn": "Кіріс байланыс",
            "msg_incoming_conn_body": "{} қосылып, файл жібергісі келеді. Рұқсат па?",
            "msg_file_request": "Файл тасымалдау сұрауы",
            "msg_file_request_body": "Жіберуші {} {} жібергісі келеді. Рұқсат па?",
            "status_calculating": "Есептелуде...",
            "status_pending": "Күтуде",
            "status_receiving": "Қабылдау",
            "status_success": "Сәтті",
            "status_error": "Қате",
            "mobile_sent": "Телефонға жіберілді",
            "peer_sender": "Жіберуші",
            "header_mobile_type": "Түрі",
            "header_mobile_file": "Файл",
            "header_mobile_size": "Өлшемі",
            "header_mobile_file": "Файл",
            "header_mobile_size": "Өлшемі",
            "header_mobile_time": "Уақыт",
            "mobile_server_stopped": "Мобильді сервер: Тоқтатылды",
            "mobile_upload": "Телефоннан жүктеу",
            "mobile_download": "Телефонға жүктеу",
            "btn_start_mobile": "Серверді қосу",
            "btn_stop_mobile": "Тоқтату",
            "btn_set_shared": "Бөлісу папкасы",
            "btn_share_files": "Файлдармен бөлісу...",
            "mobile_folder_info": "Бөлісу папкасындағы файлдар телефонда көрінеді.",
            "mobile_hist_label": "Телефон тарихы",
            "btn_clear_mobile": "Тарихты тазалау",
            "mobile_auth_code": "Қосылу коды:",
            "mobile_auth_prompt": "Қол жеткізу үшін кодты енгізіңіз",
            "mobile_auth_device_name": "Құрылғы аты:",
            "mobile_auth_invalid": "Қате код",
            "mobile_auth_success": "Қол жеткізу берілді",
            "btn_reset_code": "Кодты қалпына келтіру",
            "mobile_connections": "Авторизацияланған: {0}/{1}",
            "mobile_no_devices": "Қосылған құрылғылар жоқ",
            "select_recipients": "Алушыларды таңдау",
            "all_devices": "Барлық құрылғылар",
            "recipient_dialog_title": "Файл алушыларын таңдаңыз",
            "shared_with_all": "Бөлісілген: Барлығымен",
            "shared_with": "Бөлісілген: {0}",
            "btn_ok": "ОК",
            "btn_cancel": "Бас тарту"
        }
    }

    def __init__(self, default_lang="en"):
        super().__init__()
        self.current_lang = default_lang

    def set_language(self, lang_code):
        if lang_code in self.TRANSLATIONS:
            self.current_lang = lang_code
            self.language_changed.emit()

    def get(self, key):
        return self.TRANSLATIONS.get(self.current_lang, {}).get(key, key)
